### ISSUE TITLE
error: incompatible integer to pointer conversion assigning to 'PyObject *'

### ISSUE THREAD

**Issue by yurivict** [jonathf/numpoly#118]
Build fails:
```
./numpoly/cfunctions/cdispach.c:3036:13: warning: call to undeclared function 'PyDataType_ELSIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3036 |   __pyx_r = PyDataType_ELSIZE(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3070:13: warning: call to undeclared function 'PyDataType_ALIGNMENT'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3070 |   __pyx_r = PyDataType_ALIGNMENT(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3108:15: warning: call to undeclared function 'PyDataType_FIELDS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3108 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
      |               ^
./numpoly/cfunctions/cdispach.c:3108:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 3108 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./numpoly/cfunctions/cdispach.c:3150:15: warning: call to undeclared function 'PyDataType_NAMES'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3150 |   __pyx_t_1 = PyDataType_NAMES(__pyx_v_self);
      |               ^
./numpoly/cfunctions/cdispach.c:3150:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 3150 |   __pyx_t_1 = PyDataType_NAMES(__pyx_v_self);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./numpoly/cfunctions/cdispach.c:3188:13: warning: call to undeclared function 'PyDataType_SUBARRAY'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3188 |   __pyx_r = PyDataType_SUBARRAY(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3188:11: error: incompatible integer to pointer conversion assigning to 'PyArray_ArrayDescr *' (aka 'struct _arr_descr *') from 'int' [-Wint-conversion]
 3188 |   __pyx_r = PyDataType_SUBARRAY(__pyx_v_self);
      |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./numpoly/cfunctions/cdispach.c:3222:13: warning: call to undeclared function 'PyDataType_FLAGS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3222 |   __pyx_r = PyDataType_FLAGS(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3256:13: warning: call to undeclared function 'PyArray_MultiIter_NUMITER'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3256 |   __pyx_r = PyArray_MultiIter_NUMITER(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3290:13: warning: call to undeclared function 'PyArray_MultiIter_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3290 |   __pyx_r = PyArray_MultiIter_SIZE(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3324:13: warning: call to undeclared function 'PyArray_MultiIter_INDEX'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3324 |   __pyx_r = PyArray_MultiIter_INDEX(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3358:13: warning: call to undeclared function 'PyArray_MultiIter_NDIM'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3358 |   __pyx_r = PyArray_MultiIter_NDIM(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3392:13: warning: call to undeclared function 'PyArray_MultiIter_DIMS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3392 |   __pyx_r = PyArray_MultiIter_DIMS(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3392:11: error: incompatible integer to pointer conversion assigning to 'npy_intp *' (aka 'long *') from 'int' [-Wint-conversion]
 3392 |   __pyx_r = PyArray_MultiIter_DIMS(__pyx_v_self);
      |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./numpoly/cfunctions/cdispach.c:3426:13: warning: call to undeclared function 'PyArray_MultiIter_ITERS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3426 |   __pyx_r = PyArray_MultiIter_ITERS(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cdispach.c:3426:11: error: incompatible integer to pointer conversion assigning to 'void **' from 'int' [-Wint-conversion]
 3426 |   __pyx_r = PyArray_MultiIter_ITERS(__pyx_v_self);
      |           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13 warnings and 5 errors generated.
error: command '/usr/local/libexec/ccache/cc' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

Version: 1.3.0
Python-3.11
numpy-1.26.4
FreeBSD 14.1

**Comment by jonathf** [comment]
Can't reproduce on Linux or MacOS.

From the error and the version this is obvious the introduction to Cython in the project.

@oarcelus, any chance you are familiar with BSD or know what we would get this error for BSD and not the other platforms?

@yurivict, can we get some more information about your `cc` compiler?

**Comment by yurivict** [comment]
cc is clang-18

**Comment by jonathf** [comment]
Is it possible to try again and setting an up-to-date `gcc` as your compiler?

PyDataType_xx are set in `numpoly/cfuntions/cdispach.c`. It is auto-generated by Cython from `numpoly/cfunctions/cdistpach.pyx`.

**Comment by oarcelus** [comment]
Those errors are related to the NumPy C-API I believe. @yurivict could you try running the `np.get_include()` function to see where it points to?. In principle this should be correctly configured already in `setup.py` buu just to be sure. Otherwise I would try setting up 'gcc' as the compiler.

Python-3.12
numpy-1.26.4
Cython 3.0.11

The `gcc` compiler is the following:
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by yurivict** [comment]
> could you try running the np.get_include() function to see where it points to?

```
>>> numpy.get_include() 
'/usr/local/lib/python3.11/site-packages/numpy/core/include'
```

**Comment by yurivict** [comment]
> PyDataType_xx are set in numpoly/cfuntions/cdispach.c

```PyDataType_ELSIZE``` is called in numpoly/cfunctions/cdispach.c, but where is it declared and defined?

**Comment by oarcelus** [comment]
It looks like the C headers are correctly located. I am not familiar with BSD let me look into it. In the meantime could you try by using the `gcc` compiler instead?

You could temporarily change compiler by running `export CC=gcc export CXX=g++`. 

About the definition and declaration of the `cdispatch.c`, as pointed out by @jonathf, these files are automatically generated by `cython` from `.pyx` files. If the building process is failing then you may not be generating these files, but they should be located at `/usr/local/lib/python3.11/site-packages/numpoly/cfunctions/`.

**Comment by yurivict** [comment]
It builds successfully with gcc.

**Comment by oarcelus** [comment]
Nice!

**Comment by karlr-vestas** [comment]
I think I have a similar error. I'm trying to install `chaospy` (and therefore `numpoly`) in databricks (a cloud environment where I dont fully control the installation process). 

Here is the relevant part of the error output. 

```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      /databricks/python/lib/python3.11/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-7nezif7s/numpoly_a372760575304122a650fd7ab2794a79/numpoly/cfunctions/cdispach.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cimport numpy as np
      import numpoly
      from typing import List
      
      
      cdef List[np.ndarray] cprepare_input(
          ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cdispach.pyx:10:5: 'List' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpoly
      from typing import List
      
      
      cdef List[np.ndarray] cprepare_input(
          List[np.ndarray] inputs,
         ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cdispach.pyx:11:4: 'List' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          return output
      
      
      def cloop_function(
              object numpy_ufunc,
              List[np.ndarray] inputs,
             ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cdispach.pyx:26:8: 'List' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef List[np.ndarray] cprepare_input(
          List[np.ndarray] inputs,
          str name,
      ):
          cdef np.ndarray poly
          cdef List[np.ndarray] output = []
              ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cdispach.pyx:15:9: 'List' is not a type identifier
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef List[np.ndarray] cprepare_input(
          List[np.ndarray] inputs,
          str name,
      ):
          cdef np.ndarray poly
          cdef List[np.ndarray] output = []
                                        ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cdispach.pyx:15:35: Cannot coerce list to type '<error>'
      Compiling ./numpoly/cfunctions/cdispach.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cvalues.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cmultiply.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cfrom_attributes.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      [1/4] Cythonizing ./numpoly/cfunctions/cdispach.pyx
      Traceback (most recent call last):
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/databricks/python/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
          cythonize_one(*args)
        File "/databricks/python/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: ./numpoly/cfunctions/cdispach.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

Sorry if this is not the same error, I can create another issue. 
I just saw Cython and build issues mentioned, so I assume they are related

**Comment by oarcelus** [comment]
Hi! Which is the Cython version that you have installed? It looks like it does not support the `List` type annotation from the `typing ` module. In principle current Cython versions should support this. Honestly I am not very familiar with the databricks environment.
 
@jonathf, I see that both build issues are related to the `cdispach.pyx`. Since these functions are not really included in the current version of `numpoly` maybe we can delete them for the moment and see if errors with other modules (`cvalues.pyx`, `cmultiply.pyx`, ...) persist.

**Comment by karlr-vestas** [comment]
From [here](https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/15.4lts#installed-python-libraries) it looks like I have Cython 0.29.32

**Comment by oarcelus** [comment]
That might be a problem. That `cython` version is very old. I am using the `3.0.11` version. Indeed the error messague is already hinting the problem
`/databricks/python/lib/python3.11/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2).`

It is trying to read the `.pyx` files as if it were Python2. From the `cython` documentation.

**language_level (2/3/3str), default=None
Globally set the Python language level to be used for module compilation. Default is None, indicating compatibility with Python 3 in Cython 3.x and with Python 2 in Cython 0.x.**

So since you are using Cython 0.x version the syntax of the current `.pyx` files is incompatible with Python 2 and hence your error.

I would try to update `cython` if you can.

@jonathf, how do you think we should proceed.

**Comment by jonathf** [comment]
I have made a new release of numpoly `1.3.1` where I require `cython >= 3.0.0` during build. I've also created `1.3.2` which also removes the dispatch module.

@karlr-vestas, do you mind testing both versions? I would like to know if the upgrade is enough, or if we have limits to what to include.

**Comment by karlr-vestas** [comment]
@jonathf I tried both versions, and they both fail to install. Version 1.3.1 fails with the same message as above, it seems like it is not respecting the Cython 3 requirement. 

Version 1.3.2 fails with this message
```
      /databricks/python/lib/python3.11/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-p8a2sitp/numpoly_0b60898d1e554a9a8d089521f5eeed66/numpoly/cfunctions/cfrom_attributes.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpoly
      from typing import List
      
      
      def cfrom_attributes(
          List[np.ndarray] coeffs,
         ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cfrom_attributes.pyx:11:4: 'List' is not a type identifier
      Compiling ./numpoly/cfunctions/cfrom_attributes.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cmultiply.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cvalues.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      [1/3] Cythonizing ./numpoly/cfunctions/cfrom_attributes.pyx
      Traceback (most recent call last):
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/databricks/python/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
          cythonize_one(*args)
        File "/databricks/python/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: ./numpoly/cfunctions/cfrom_attributes.pyx
      [end of output]
  ```

**Comment by karlr-vestas** [comment]
Just for completeness, I also tested v 1.2.14, and that installs without issues

**Comment by karlr-vestas** [comment]
This is the environment I'm running in: https://learn.microsoft.com/en-us/azure/databricks/release-notes/runtime/15.4lts#installed-python-libraries

**Comment by oarcelus** [comment]
@jonathf can we try the following specification in the `setup.py` file?

    setup(
        ext_modules=cythonize(
            extensions,
            compiler_directives={"language_level": "3"},  # Explicitly set to Python 3
        ),
    )

Maybe this works?

**Comment by karlr-vestas** [comment]
@jonathf I think that was an issue on my end. There might be some caching going on or something. I ran it now, I get this error

```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      import numpoly
      from typing import List
      
      
      def cfrom_attributes(
          List[np.ndarray] coeffs,
         ^
      ------------------------------------------------------------
      
      numpoly/cfunctions/cfrom_attributes.pyx:11:4: 'List' is not a type identifier
      Compiling ./numpoly/cfunctions/cvalues.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cmultiply.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      Compiling ./numpoly/cfunctions/cfrom_attributes.pyx because it depends on /databricks/python/lib/python3.11/site-packages/numpy/__init__.pxd.
      [1/3] Cythonizing ./numpoly/cfunctions/cfrom_attributes.pyx
      Traceback (most recent call last):
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/databricks/python/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 16, in <module>
        File "/databricks/python/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
          cythonize_one(*args)
        File "/databricks/python/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: ./numpoly/cfunctions/cfrom_attributes.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by yurivict** [comment]
1.3.3 has the same problem.

The reason the build fails with clang is that clang made the "incompatible integer to pointer conversion" warning an error, and gcc keeps it as warning.

But the C code in cfrom_attributes.c is certanly invalid.

clang messages:
```
In file included from ./numpoly/cfunctions/cfrom_attributes.c:1249:
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5:
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929:
/usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^
./numpoly/cfunctions/cfrom_attributes.c:3000:13: warning: call to undeclared function 'PyDataType_ELSIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3000 |   __pyx_r = PyDataType_ELSIZE(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cfrom_attributes.c:3034:13: warning: call to undeclared function 'PyDataType_ALIGNMENT'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3034 |   __pyx_r = PyDataType_ALIGNMENT(__pyx_v_self);
      |             ^
./numpoly/cfunctions/cfrom_attributes.c:3072:15: warning: call to undeclared function 'PyDataType_FIELDS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 3072 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
      |               ^
./numpoly/cfunctions/cfrom_attributes.c:3072:13: error: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
 3072 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
      |             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

gcc messages:
```
In file included from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ./numpoly/cfunctions/cfrom_attributes.c:1249:
/usr/local/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
./numpoly/cfunctions/cfrom_attributes.c: In function '__pyx_f_5numpy_5dtype_8itemsize_itemsize':
./numpoly/cfunctions/cfrom_attributes.c:3000:13: warning: implicit declaration of function 'PyDataType_ELSIZE'; did you mean 'PyDataType_ISUNSIZED'? [-Wimplicit-function-declaration]
 3000 |   __pyx_r = PyDataType_ELSIZE(__pyx_v_self);
      |             ^~~~~~~~~~~~~~~~~
      |             PyDataType_ISUNSIZED
./numpoly/cfunctions/cfrom_attributes.c: In function '__pyx_f_5numpy_5dtype_9alignment_alignment':
./numpoly/cfunctions/cfrom_attributes.c:3034:13: warning: implicit declaration of function 'PyDataType_ALIGNMENT'; did you mean 'PyDataType_ISSIGNED'? [-Wimplicit-function-declaration]
 3034 |   __pyx_r = PyDataType_ALIGNMENT(__pyx_v_self);
      |             ^~~~~~~~~~~~~~~~~~~~
      |             PyDataType_ISSIGNED
./numpoly/cfunctions/cfrom_attributes.c: In function '__pyx_f_5numpy_5dtype_6fields_fields':
./numpoly/cfunctions/cfrom_attributes.c:3072:15: warning: implicit declaration of function 'PyDataType_FIELDS'; did you mean 'PyDataType_HASFIELDS'? [-Wimplicit-function-declaration]
 3072 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
      |               ^~~~~~~~~~~~~~~~~
      |               PyDataType_HASFIELDS
./numpoly/cfunctions/cfrom_attributes.c:3072:13: warning: assignment to 'PyObject *' {aka 'struct _object *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
 3072 |   __pyx_t_1 = PyDataType_FIELDS(__pyx_v_self);
```

**Comment by oarcelus** [comment]
@yurivict I am surprised about the errors. I have tried to reproduce it but I don't seem to manage.

Cython             3.0.11
numpoly           1.3.2
numpy              2.1.3

I installed `clang` in Ubuntu with `sudo apt install clang`.

Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bi

From a fresh virtual environment, I downloaded the current master branch. I modified the `setup.py`:

    from setuptools import setup, Extension
    from Cython.Build import cythonize
    import numpy as np
    import os
    
    extensions = [
        Extension(
            name="numpoly.cfunctions." + item.replace(".pyx", ""),  # Name of the extension module
            sources=["./numpoly/cfunctions/" + item],  # Path to your `.pyx` file
            include_dirs=[np.get_include()],  # Include NumPy headers
        )
        for item in os.listdir("./numpoly/cfunctions/") if ".pyx" in item
    ]
    
    # Setup configuration
    setup(
        ext_modules=cythonize(extensions, compiler_directives={"language_level": 3}, verbose=True),  # Compile the Cython files
        include_dirs=[np.get_include()],  # Include NumPy headers
)

I set `clang` as my compiler and run:

    python setup.py build_ext --inplace --verbose
    pip install .
    pytest --doctest-modules numpoly/ test/

All tests pass correctly. As well as my own tests. The only warning I get are related to the deprecated C_API of NUMPY.

      running build_ext
      building 'numpoly.cfunctions.cvalues' extension
      creating build/temp.linux-x86_64-cpython-313/numpoly/cfunctions
      clang -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/oarcelus/anaconda3/envs/numpoly/include -fPIC -O2 -isystem /home/oarcelus/anaconda3/envs/numpoly/include -fPIC -I/home/oarcelus/anaconda3/envs/numpoly/lib/python3.13/site-packages/numpy/_core/include -I/home/oarcelus/anaconda3/envs/numpoly/lib/python3.13/site-packages/numpy/_core/include -I/home/oarcelus/anaconda3/envs/numpoly/include/python3.13 -c ./numpoly/cfunctions/cvalues.c -o build/temp.linux-x86_64-cpython-313/./numpoly/cfunctions/cvalues.o
      In file included from ./numpoly/cfunctions/cvalues.c:1249:
      In file included from /home/oarcelus/anaconda3/envs/numpoly/lib/python3.13/site-packages/numpy/_core/include/numpy/arrayobject.h:5:
      In file included from /home/oarcelus/anaconda3/envs/numpoly/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12:
      In file included from /home/oarcelus/anaconda3/envs/numpoly/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909:
      /home/oarcelus/anaconda3/envs/numpoly/lib/python3.13/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
      #warning "Using deprecated NumPy API, disable it with " \
       ^
      1 warning generated.

Can you guide me a little bit on how are you setting up your system?

**Comment by jonathf** [comment]
@yurivict, are you saying that gcc worked for 1.3.0, but doesn't for 1.3.3? Do you mind reporting how it fairs for 1.3.1 and 1.3.2 as well so we better know what broke it?

I think we are getting to the point where we need to consider setting up cibuildwheel. This will take a little time to do though since I am busy these days.

@yurivict, do you know if BSD works and behaves well with cibuildwheel?

**Comment by oarcelus** [comment]
@karlr-vestas. I have tried to solve the problem with `cython==0.X`. I built an environment trying to be close to what you sent from databricks

Python             3.11
Cython             0.29.32
numpoly            1.3.2
numpy              2.1.3

Indeed, your error appeared when trying to build the package directly from the repo.

@jonathf, the solution is to eliminate the `List` type from the `typing` module, and replace it with a plain `list`. For me it worked with `gcc` and `clang`. 

In `cmultiply.pyx`

    cdef void cmultiply_cdef(
            np.ndarray[np.uint32_t, ndim=2] expons1,
            np.ndarray[np.uint32_t, ndim=2] expons2,
            list coeffs1,
            list coeffs2,
            int offset,
            np.ndarray out,
    )

And in `cfrom_attributes.pyx`

    def cfrom_attributes(
        list coeffs,
        np.ndarray poly
    ):
  
Also, again I set the `setup.py` file like this. 

    from setuptools import setup, Extension
    from Cython.Build import cythonize
    import numpy as np
    import os
    
    extensions = [
        Extension(
            name="numpoly.cfunctions." + item.replace(".pyx", ""),  # Name of the extension module
            sources=["./numpoly/cfunctions/" + item],  # Path to your `.pyx` file
            include_dirs=[np.get_include()],  # Include NumPy headers
        )
        for item in os.listdir("./numpoly/cfunctions/") if ".pyx" in item
    ]
    
    # Setup configuration
    setup(
        ext_modules=cythonize(extensions, compiler_directives={"language_level": 3}, verbose=True),  # Compile the Cython files
        include_dirs=[np.get_include()],  # Include NumPy headers

I still prefer to be more stringent with the type annotation and use `List[np.ndarray]` instead of `list`. Maybe we can create two versions? One that is backcompatible with `cython==0.X` and the other that requires `cython==3.X`?

**Comment by jonathf** [comment]
Well done @oarcelus. That made 0.X work on my system as well.

@yurivict, @karlr-vestas, do you mind testing version 1.3.4?

**Comment by karlr-vestas** [comment]
@jonathf 1.3.4 seems to be working for me. Thanks!

**Comment by yurivict** [comment]
1.3.6 has the same problem.

gcc is able to compile it with warnings like this one:
```
./numpoly/cfunctions/cvalues.c:18400:11: warning: assignment to 'void **' from 'int' makes pointer from integer without a cast [-Wint-conversion]
18400 |   __pyx_r = PyArray_MultiIter_ITERS(__pyx_v_self);
      |           ^
```

This should really be an error.

We use numpy-1.26.4

numpy-2.x isn't generally available in many distros due to conflicts with numpy-1.x: many Python packages still require numpy-1.x

**Comment by jonathf** [comment]
There has been two major updates lately: One for updating speed using Cython and one updating Numpy interface for future proofing. Neither of these update affects the interface to Chaospy.

Would a solution be to make two version lines of numpoly? one base on 1.2 with numpy v1, and one on 1.3 with numpy v2+Cython?

If we go for such a solution I will likely have to remove 1.3.0-1.3.4 to not confuse dependency resolution, but seems like a simpler solution than to maintain support for two incompatible versions of numpy, and it solves your compile issues for the time being.
